export enum Region {
    TANGER_TETOUAN_AL_HOCEIMA,
    ORIENTAL,
    FES_MEKNES,
    RABAT_SALE_KENITRA,
    BENI_MELLAL_KHENIFRA,
    CASABLANCA_SETTAT,
    MARRAKECH_SAFI,
    DRAA_TAFILALET,
    SOUSS_MASSA,
    GUELMIM_OUED_NOUN,
    LAAYOUNE_SAKIA_EL_HAMRA,
    DAKHLA_OUED_EDDAHAB
}
