export enum Region {
    TANGER_TETOUAN_AL_HOCEIMA = "TANGER_TETOUAN_AL_HOCEIMA",
    ORIENTAL = "ORIENTAL",
    FES_MEKNES = "FES_MEKNES",
    RABAT_SALE_KENITRA = "RABAT_SALE_KENITRA",
    BENI_MELLAL_KHENIFRA = "BENI_MELLAL_KHENIFRA",
    CASABLANCA_SETTAT = "CASABLANCA_SETTAT",
    MARRAKECH_SAFI = "MARRAKECH_SAFI",
    DRAA_TAFILALET = "DRAA_TAFILALET",
    SOUSS_MASSA = "SOUSS_MASSA",
    GUELMIM_OUED_NOUN = "GUELMIM_OUED_NOUN",
    LAAYOUNE_SAKIA_EL_HAMRA = "LAAYOUNE_SAKIA_EL_HAMRA",
    DAKHLA_OUED_EDDAHAB = "DAKHLA_OUED_EDDAHAB"
}
