export enum StageLevel {
    ROUND_OF_128_ELIMINATION =  "ROUND_OF_128_ELIMINATION",
    ROUND_OF_64_ELIMINATION= "ROUND_OF_64_ELIMINATION",
    ROUND_OF_32_ELIMINATION="ROUND_OF_32_ELIMINATION",
    ROUND_OF_16_ELIMINATION="ROUND_OF_16_ELIMINATION",
    QUARTERFINAL_ELIMINATION="QUARTERFINAL_ELIMINATION",
    SEMIFINAL_ELIMINATION= "SEMIFINAL_ELIMINATION",
    FINAL_ELIMINATION="FINAL_ELIMINATION",
    POINTS_STAGE_GROUP="POINTS_STAGE_GROUP",
    POINTS_STAGE_FINAL="POINTS_STAGE_FINAL"
}
